### ISSUE TITLE
Submit to asdf-plugins

### ISSUE THREAD

**Issue by rakuyoMo** [mollyIV/asdf-fastlane#1]
[asdf-plugins](https://github.com/asdf-vm/asdf-plugins) contains a lot of plugins. After submitting the plugin to the repository, users can use the plugin without declaring `plugin`.

Fastlane is widely used. I suggest you try submitting this plugin to asdf-plugins.

**Comment by mollyIV** [comment]
Thanks for the suggestion, the pull request has been created: https://github.com/asdf-vm/asdf-plugins/pull/1031

**Comment by mollyIV** [comment]
The pull request has been merged into [asdf-plugins](https://github.com/asdf-vm/asdf-plugins) repository. I'm closing the ticket.
